### ISSUE TITLE
Download of .vsix extension file

### ISSUE THREAD

**Issue by marc4F** [wozjac/vscode-ui5-odata-mock-generator#1]
Hi

thanks for this great extension!

Is it possible to include the .vsix file inside this github repo?
This way it can be manually installed inside Business Application Studio.

I could in theory download it from microsofts store. But then it is only allowed to be used inside vscode.
quote:
_Downloading extensions from the Microsoft Marketplace for any use other than in Microsoft products is prohibited_
https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php

**Comment by wozjac** [comment]
Thanks!

Here you go: https://github.com/wozjac/vscode-ui5-odata-mock-generator/releases/tag/v1.0.0

BR,
Jacek

**Comment by wozjac** [comment]
Closed, resolved.
